### ISSUE TITLE
Hard-coded values

### ISSUE THREAD

**Issue by MrToph** [Dylan-Phoon/TradEOS1#1]
Hi, just had a quick look at how other people write EOS smart contracts, why is `1926` hard-coded here?
https://github.com/Dylan-Phoon/TradEOS1/blob/653fd7ec8fb16e547649cd0c029d39bb43edfbe5/exchange.cpp#L156

**Comment by Dylan-Phoon** [comment]
It's just an arbitrary key for looking up the counter in the given table. Because there is always only one counter in a table, we can assign a single key for lookup. It could be changed to anything but the id in the counter structs would also have to be changed so that they match.
